import type { MenuCategory, MenuDetail } from "../types/user";

export const MOCK_CATEGORIES: MenuCategory[] = [
  {
    categoryId: 1,
    categoryName: "컵밥",
    displayOrder: 1,
    menus: [
      {
        id: 1,
        name: "삼겹소금",
        description: "노릇하게 구운 삼겹살에 소금을 더해 담백한 풍미를 살린 컵밥",
        basePrice: 3600,
        imageUrl: null, // 피그마 캡처 상 '사진' 대체텍스트 형태로 되어 있음
        displayOrder: 1,
        saleStatus: "AVAILABLE",
      },
      {
        id: 2,
        name: "삼겹제육",
        description: "매콤한 제육 양념이 삼겹살에 깊게 배어 감칠맛을 더한 컵밥",
        basePrice: 3600,
        imageUrl: null,
        displayOrder: 2,
        saleStatus: "AVAILABLE",
      },
    ],
  },
  {
    categoryId: 2,
    categoryName: "우동",
    displayOrder: 2,
    menus: [
      {
        id: 3,
        name: "냉모밀",
        description: "시원한 육수와 쫄깃한 메밀면으로 더위를 날려줄 한 그릇",
        basePrice: 5500,
        imageUrl: null,
        displayOrder: 1,
        saleStatus: "AVAILABLE",
      },
    ],
  },
  {
    categoryId: 3,
    categoryName: "세트",
    displayOrder: 3,
    menus: [], // 빈 카테고리 예외 대응
  },
  {
    categoryId: 4,
    categoryName: "음료",
    displayOrder: 4,
    menus: [
      {
        id: 4,
        name: "생수",
        description: "시원한 천연 암반수",
        basePrice: 1000,
        imageUrl: null,
        displayOrder: 1,
        saleStatus: "AVAILABLE",
      },
    ],
  },
];

export const MOCK_MENU_DETAILS: Record<number, MenuDetail> = {
  1: {
    id: 1,
    categoryId: 1,
    categoryName: "컵밥",
    name: "삼겹소금",
    description: "노릇하게 구운 삼겹살에 소금을 더해 담백한 풍미를 살린 컵밥",
    basePrice: 3600,
    imageUrl: null,
    displayOrder: 1,
    saleStatus: "AVAILABLE",
    options: [
      {
        id: 101,
        groupType: "SIZE",
        name: "기본",
        additionalPrice: 0,
        maxQuantity: 1,
        defaultSelected: true,
        displayOrder: 1,
      },
      {
        id: 102,
        groupType: "SIZE",
        name: "더블",
        additionalPrice: 1000,
        maxQuantity: 1,
        defaultSelected: false,
        displayOrder: 2,
      },
      {
        id: 103,
        groupType: "SIZE",
        name: "점보",
        additionalPrice: 2000,
        maxQuantity: 1,
        defaultSelected: false,
        displayOrder: 3,
      },
      {
        id: 104,
        groupType: "TOPPING_ADD",
        name: "계란후라이",
        additionalPrice: 700,
        maxQuantity: 3, // 계란후라이 최대 수량 3
        defaultSelected: false,
        displayOrder: 4,
      },
      {
        id: 105,
        groupType: "TOPPING_ADD",
        name: "고기 추가",
        additionalPrice: 1000,
        maxQuantity: 3, // 고기 추가 최대 수량 3
        defaultSelected: false,
        displayOrder: 5,
      },
      {
        id: 106,
        groupType: "TOPPING_ADD",
        name: "밥 추가",
        additionalPrice: 1000,
        maxQuantity: 3, // 밥 추가 최대 수량 3
        defaultSelected: false,
        displayOrder: 6,
      },
      {
        id: 107,
        groupType: "TOPPING_REMOVE",
        name: "김치 제외",
        additionalPrice: 0,
        maxQuantity: 1,
        defaultSelected: false,
        displayOrder: 7,
      },
      {
        id: 108,
        groupType: "TOPPING_REMOVE",
        name: "고추장소스 제외",
        additionalPrice: 0,
        maxQuantity: 1,
        defaultSelected: false,
        displayOrder: 8,
      },
    ],
  },
  2: {
    id: 2,
    categoryId: 1,
    categoryName: "컵밥",
    name: "삼겹제육",
    description: "매콤한 제육 양념이 삼겹살에 깊게 배어 감칠맛을 더한 컵밥",
    basePrice: 3600,
    imageUrl: null,
    displayOrder: 2,
    saleStatus: "AVAILABLE",
    options: [
      {
        id: 201,
        groupType: "SIZE",
        name: "기본",
        additionalPrice: 0,
        maxQuantity: 1,
        defaultSelected: true,
        displayOrder: 1,
      },
      {
        id: 202,
        groupType: "SIZE",
        name: "더블",
        additionalPrice: 1000,
        maxQuantity: 1,
        defaultSelected: false,
        displayOrder: 2,
      },
    ],
  },
  3: {
    id: 3,
    categoryId: 2,
    categoryName: "우동",
    name: "냉모밀",
    description: "시원한 육수와 쫄깃한 메밀면으로 더위를 날려줄 한 그릇",
    basePrice: 5500,
    imageUrl: null,
    displayOrder: 1,
    saleStatus: "AVAILABLE",
    options: [],
  },
  4: {
    id: 4,
    categoryId: 4,
    categoryName: "음료",
    name: "생수",
    description: "시원한 천연 암반수",
    basePrice: 1000,
    imageUrl: null,
    displayOrder: 1,
    saleStatus: "AVAILABLE",
    options: [],
  },
};
